<?php
/**
 * Class billet
 *
 * @author      Open Source Team
 * @copyright   2021 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 *
 * @link        https://pagar.me
 */
?>

<?php if ($this->getBilletUrl()): ?>

    <div align="center">
        <table width="85%" style="border-collapse: collapse; border: none;">
            <tr style="border: none;">
                <td align="center" style="border: none;">
                    <hr />
                    <a class="action tocart primary" id="pagarme-link-boleto" href="<?php echo $this->getBilletUrl() ?>" target="_blank"><?php echo __('Print Billet') ?></a>
                </td>
            </tr>
        </table>
    </div>
    
<?php endif ?>

